workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: ELVIN TORRES
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: live.captureit.app
      vars:
        BUNDLE_ID: "live.captureit.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install
      - name: Set up keychain
        script: keychain initialize
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Fetch provisioning profiles
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
